workflow done again

diff --git a/.github/workflows/module4_task0.yml b/.github/workflows/module4_task0.yml
--- a/.github/workflows/module4_task0.yml
+++ b/.github/workflows/module4_task0.yml
@@ -1,63 +1,83 @@
-# Help on commands
-help: ## Show this help
-	@sed -ne '/@sed/!s/## //p' $(MAKEFILE_LIST)
+---
+env:
+  GH_TOKEN: ${{ github.token }}
+name: module3_task5
+"on":
+  push:
+    tags: "1.0.1"
+    branches:
+      - main
+  schedule:
+    - cron: '0 0 * * *'
+  pull_request:
+    types: [opened, reopened, synchronize]
 
-# Build the website
-build: ## Build the go and the dist
-	make lint && go build
-	make check && make validate && hugo
+permissions: read-all
 
-# Run the website
-run: ## Run the website
-	make build
-	./awesome-api >./awesome.log 2>&1 &
+jobs:
+  builds:
+    permissions: write-all
+    name: job1
+    runs-on: ubuntu-18.04
+    container: golang:1.15.8-buster
 
-# Stop the website
-stop: ## Stop the website
-	pkill awesome-api || true
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: 16
+      - name: install markdownlint
+        run: npm install -g markdownlint-cli
 
-# Clean up the project
-clean: ## Clean up the project
-	make stop
-	rm -f awesome* coverage*
-	rm -rf dist
+      - name: install markdown-link-check
+        run: npm install -g markdown-link-check
 
-# Create a new blog post
-post: ## Create a new blog post
-	hugo new ./content/posts/$(POST_NAME).md
-	sed -i 's/title: .*/title: "$(POST_TITLE)"/g' ./content/posts/$(POST_NAME).md
+      - name: install hugo
+        run: cd module4_task0 && ./setup.sh
 
-# Check the markdown files
-check: ## Check the markdown files
-	markdownlint ./content/posts/*
-	markdown-link-check ./content/posts/*
+      - name: Validate Makefile
+        run:
+          cd module4_task0
+          make lint
+          make build
+          make package
+          make unit-tests
+          make integration-tests
+          make validate
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        if: startsWith(github.ref, 'refs/tags/1.0.1')
+        with:
+          files: |
+            awesome-website.zip
+            DEPLOY.md
+          body: |
+            # First project
+            What is in the archive and how to unarchive it? zip
+            What are the commands to start and stop the application? tag
+            How to customize where the application logs are written?
+            How to verify that the application is runing (healthcheck)?
+      - run: gh release create v1.0.1 --title "v1.0.1" --notes DEPLOY.md\
+            2>/dev/null || echo "OK"
+      - name: release drafter
+        uses: release-drafter/release-drafter@v5
+      - name: deploy
+        uses: nwtgck/actions-netlify@v1
+        env:
+          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
+          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
+        with:
+          deploy-message: "Deploy from GitHub Actions"
+          publish-dir: "module4_task0/dist"
+          production-branch: main
+          enable-pull-request-comment: true
+          overwrites-pull-request-comment: true
+          enable-commit-comment: true
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
-# Validate the website
-validate: ## Validate the website
-	./W3C-Validator/w3c_validator.py ./dist/index.html || true
-
-# tests the files
-test: ## test the files
-	make unit-tests
-	make integration-tests
-
-# Create an archive file containing the dist/ directory
-package: ## Create an archive file containing the dist/ directory
-	hugo
-	zip -r awesome-website.zip dist/
-
-# lint the main.go
-lint: ## lint the main.go
-	golangci-lint run
-	markdownlint README.md
-	markdownlint DEPLOY.md
-	
-# unit-tests the main.go
-unit-tests: ## unit-tests the main.go
-	go test -v -short -coverprofile=coverage-units.out
-
-# integration-tests
-integration-tests: ## integration-tests
-	go test -v -coverprofile=coverage-integrations.out
-# Set default target
-.PHONY: build clean run stop test lint unit-tests integration-tests check validate package
+# valid inputs are ['publish-dir', 'functions-dir', 'deploy-message',
+# 'github-token', 'production-branch', 'production-deploy',
+# 'enable-pull-request-comment', 'enable-commit-comment',
+# 'enable-commit-status', 'overwrites-pull-request-comment',
+# 'netlify-config-path', 'alias', 'github-deployment-environment',
+# 'github-deployment-description', 'fails-without-credentials']
